services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: realestate-sql
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - realestate_net

  api:
    build:
      context: .
      dockerfile: RealEstate.API/Dockerfile
    container_name: realestate-api
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__DefaultConnection: >
        Server=${DB_HOST};
        Database=${DB_NAME};
        User Id=${DB_USER};
        Password=${DB_PASSWORD};
        TrustServerCertificate=True;
    networks:
      - realestate_net

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    depends_on:
      - sqlserver
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - realestate_net

volumes:
  sql_data:
  cloudbeaver_data:

networks:
  realestate_net:
    driver: bridge
